name: noexis_task
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get:
  cupertino_icons: ^1.0.2
  firebase_core: ^2.19.0
  firebase_auth: ^4.11.1
  google_maps_flutter: ^2.5.0
  image_picker: ^1.0.4
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  firebase_storage: ^11.3.1
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
